### ISSUE TITLE
Certificates to Gain

### ISSUE THREAD

**Issue by theccollins** [theccollins/careerManagement#1]
- [ ] [Google IT Support Professional Certificate](https://grow.google/programs/it-support/)
- [ ] [PMP](https://www.pmi.org/) - Project Management Professional: https://github.com/thecececollins/careerManagement/issues/2
- [ ] Project Management Body of Knowledge [PMBOK]
- [ ] [ITF](https://certification.comptia.org/certifications/it-fundamentals) - CompTIA IT Fundamentals
- [ ] [CompTIA Project+](https://certification.comptia.org/certifications/project)
- [ ] CompTIA Strata Green IT
- [ ] CompTIA A+
- [ ] Network+
- [ ] Security+
- [ ] ANSI
- [ ] CCENT
- [ ] CCNA
- [ ] ISO standards Scaled Agile Framework (SAFe) PCI compliance
- [ ] [MCTS](https://www.microsoft.com/en-us/learning/mcts-certification.aspx) – Microsoft Certified Technology Specialist
- [ ] ITIL best practice processes
- [ ] ITIL Foundation Level certification
- [ ] ITIL Service Manager or Operations Certification A+ Certification
